[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.nixpacks]
providers = ["python"]
aptPkgs = ["zlib1g-dev", "libjpeg-dev"]

[[mounts]]
source = "data"
mountPath = "/app/data"
